name: Deploy

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key and known hosts
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > keyfile
        chmod 600 keyfile
        mkdir -p ~/.ssh
        ssh-keyscan -t rsa ec2-3-149-27-166.us-east-2.compute.amazonaws.com >> ~/.ssh/known_hosts

    - name: Upload deploy script
      run: |
        scp -i keyfile -o StrictHostKeyChecking=no ./deploy.sh ubuntu@ec2-3-149-27-166.us-east-2.compute.amazonaws.com:~/deploy.sh

    - name: Set script permissions
      run: |
        ssh -i keyfile -o StrictHostKeyChecking=no ubuntu@ec2-3-149-27-166.us-east-2.compute.amazonaws.com "chmod +x ~/deploy.sh"

    - name: SSH into EC2 and deploy
      run: |
        ssh -i keyfile -o StrictHostKeyChecking=no ubuntu@ec2-3-149-27-166.us-east-2.compute.amazonaws.com "sudo bash ~/deploy.sh"
